### ISSUE TITLE
Upgrade to Metals v0.7.6

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals-eclipse#3]
Metals v0.7.6 was recently released http://scalameta.org/metals/blog/2019/09/23/thorium.html

What would be needed to upgrade to the latest release? Could we maybe automate it somehow in the Metals release process so that the Eclipse plugin stays up to date?

**Comment by mundacho** [comment]
In Eclipse I use coursier to get and install metals. It just requires just to change the version hard coded in the code. A better solution I guess is to publish the latest metals version somewhen and the Eclipse metals plugin can just get that to launch metals. That way, the user doesn't even need to update.

**Comment by DavidGoodenough** [comment]
Remember that not all uses of eclipse are online.  So the checking for a new version must fail quickly and not slow down the startup of eclipse or the first opening of a scala file just because the repository can not be reached.  Can it not be done from the metals web console (localhost:5031)?

**Comment by mundacho** [comment]
@DavidGoodenough I'm not sure what do you mean with the web console, the console to launch build etc? That is not integrated with eclipse, so that would mean that it's a metals feature and not am eclipse-metals issue . In theory, coursier caches the metals jar, so only the first time you should have an issue with if the repo cannot be reached. I'll update Eclipse metals tomorrow for the short term and share my findings about the best update mechanism here to discuss with you.

**Comment by olafurpg** [comment]
One possible solution could be to use the version `latest.stable`, coursier caches the results for 24hr by default.

```
coursier fetch org.scalameta:metals_2.12:latest.stable
```

**Comment by mundacho** [comment]
Is there also an option to get the latest snapshot?

**Comment by olafurpg** [comment]
I'm not aware of such an option. I think it's better to let people explicitly type out the snapshot version.

**Comment by mundacho** [comment]
ok
